# Generated by Django 5.2.6 on 2025-09-29 17:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_file', models.FileField(upload_to='datasets/')),
                ('delimiter', models.CharField(default=',', max_length=4)),
                ('encoding', models.CharField(default='UTF-8', max_length=32)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DatasetColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_in_file', models.CharField(max_length=200)),
                ('mapped_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('ID', 'ID'), ('TEXT', 'TEXT'), ('FEATURE', 'FEATURE'), ('LABEL', 'LABEL'), ('IGNORE', 'IGNORE')], default='FEATURE', max_length=10)),
                ('dtype', models.CharField(default='string', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='core.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('data', models.JSONField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.dataset')),
            ],
            options={
                'unique_together': {('dataset', 'row_index')},
            },
        ),
    ]
